---
driver:
  name: vagrant

provisioner:
  name: nodes

driver_config:
  network:
    - ["private_network", { type: "dhcp" }]
    - ["forwarded_port", { guest: 9200, host: 9200 }]
    - ["forwarded_port", { guest: 5959, host: 5959 }]
  vagrantfiles:
  - VagrantAdditionalConfig.rb
